"""
Documentation Generator - Creates project documentation for SpecPulse

This module generates AI integration guides, fallback procedures, and other
project documentation. Extracted from specpulse.py to reduce complexity.
"""

from pathlib import Path
from datetime import datetime
from typing import Optional

from .. import __version__


def create_documentation(project_path: Path) -> None:
    """
    Create centralized documentation for AI commands and fallback procedures.

    Args:
        project_path: Path to the project root
    """
    docs_dir = project_path / ".specpulse" / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)

    # Create all documentation files
    _create_fallback_guide(docs_dir)
    _create_integration_guide(docs_dir)
    _create_docs_readme(docs_dir)


def _create_fallback_guide(docs_dir: Path) -> None:
    """Create the AI Fallback Guide documentation"""
    content = f"""# SpecPulse AI Fallback Guide

This guide provides fallback procedures when SpecPulse CLI commands fail.

## CLI Failure Detection

AI should detect CLI failures through:

1. **Exit codes**: Non-zero exit codes indicate failure
2. **Error patterns**: "command not found", "No such file", "Permission denied"
3. **Timeout**: Commands taking too long (>30 seconds)
4. **Missing dependencies**: Required tools not available

## Standard Fallback Procedures

### 1. Directory Structure Creation

**CLI Command**: `specpulse feature init <name>`

**Fallback**: Manual directory creation

```bash
PROJECT_ROOT=$(pwd)
FEATURE_DIR="$PROJECT_ROOT/.specpulse/specs/001-feature-name"
mkdir -p "$FEATURE_DIR"
mkdir -p "$PROJECT_ROOT/.specpulse/plans/001-feature-name"
mkdir -p "$PROJECT_ROOT/.specpulse/tasks/001-feature-name"
```

### 2. Specification Creation

**CLI Command**: `specpulse spec create "description"`

**Fallback**: Create spec file manually with this template:

```markdown
# Specification: [DESCRIPTION]

<!-- FEATURE_DIR: 001-feature-name -->
<!-- FEATURE_ID: 001 -->
<!-- SPEC_NUMBER: 001 -->
<!-- STATUS: pending -->

## Description

[DESCRIPTION]

## Requirements

### Functional Requirements

- [ ] Requirement 1
- [ ] Requirement 2

### Non-Functional Requirements

- [ ] Performance requirement
- [ ] Security requirement

## Acceptance Criteria

- [ ] Criteria 1
- [ ] Criteria 2
```

### 3. Plan Creation

**CLI Command**: `specpulse plan create "description"`

**Fallback**: Create plan file manually with embedded template.

### 4. Task Breakdown

**CLI Command**: `specpulse task breakdown <plan-id>`

**Fallback**: Create task files manually with proper metadata.

## Error Recovery

### Permission Errors

```bash
chmod -R 755 "$PROJECT_ROOT/.specpulse"
```

### Path Issues

```bash
PROJECT_ROOT=$(pwd -P)
```

## AI Integration Best Practices

1. **Always try CLI first**
2. **Check exit code and output**
3. **If failed, apply fallback immediately**
4. **Log the fallback usage**

## When to Escalate

Escalate to manual intervention when:

- Multiple fallbacks fail in sequence
- Critical system dependencies are missing
- File permissions cannot be resolved

**Remember: AI should always enable work to continue, even when tooling fails!**

---

*Generated by SpecPulse v{__version__}*
*Created: {datetime.now().strftime('%Y-%m-%d')}*
"""
    with open(docs_dir / "AI_FALLBACK_GUIDE.md", 'w', encoding='utf-8') as f:
        f.write(content)


def _create_integration_guide(docs_dir: Path) -> None:
    """Create the AI Integration Guide documentation"""
    content = f"""# SpecPulse AI Integration Guide

This guide explains how AI assistants integrate with SpecPulse.

## Supported AI Platforms

### Claude Code

- **Location**: `.claude/commands/`
- **Commands**: `/sp-*` slash commands
- **Files**: Markdown format (.md)

### Gemini CLI

- **Location**: `.gemini/commands/`
- **Commands**: `/sp-*` commands
- **Files**: TOML format (.toml)

### Other Platforms

- **Windsurf**: `.windsurf/workflows/`
- **Cursor**: `.cursor/commands/`
- **GitHub Copilot**: `.github/prompts/`
- **OpenCode**: `.opencode/command/`
- **Crush**: `.crush/commands/sp/`
- **Qwen Code**: `.qwen/commands/`

## CLI-AI Collaboration Pattern

### Critical Design Principle: CLI First, AI Enhanced

```
User Request → AI Command → CLI Command → File Creation → AI Enhancement
```

1. **AI Command Detection**: AI detects intent and routes to CLI
2. **CLI Command Execution**: CLI creates foundation (directories, templates)
3. **AI Content Enhancement**: AI expands templates with detailed content

## Command Reference

### Feature Management

```bash
/sp-pulse <feature-name>     # Initialize feature
/sp-continue <feature-id>    # Switch to existing feature
/sp-status                   # Show project status
```

### Specification Management

```bash
/sp-spec "description"       # Create specification
/sp-validate                 # Validate all specs
```

### Planning & Tasks

```bash
/sp-plan                     # Generate implementation plan
/sp-task                     # Create task breakdown
/sp-execute                  # Execute next task
```

## Workflow Example

1. **Initialize Feature**: `/sp-pulse user-authentication`
2. **Create Specification**: `/sp-spec "OAuth2 login with JWT"`
3. **Generate Plan**: `/sp-plan`
4. **Break Down Tasks**: `/sp-task`
5. **Execute Tasks**: `/sp-execute`

## Error Handling

When CLI fails:

1. Apply fallback procedures (see AI_FALLBACK_GUIDE.md)
2. Use embedded templates
3. Log the failure
4. Continue work without stopping

## Best Practices

1. **Always try CLI first** - CLI provides structure and consistency
2. **Use fallbacks gracefully** - Never let user workflows stop
3. **Enhance, don't replace** - AI adds value to CLI foundation
4. **Maintain context** - Track project state and user preferences
5. **Validate continuously** - Ensure quality and completeness

## Resources

- **AI Fallback Guide**: `.specpulse/docs/AI_FALLBACK_GUIDE.md`
- **Project Status**: `.specpulse/memory/context.md`
- **Validation Rules**: `.specpulse/validation_rules.yaml`
- **Templates**: `.specpulse/templates/`

---

*Generated by SpecPulse v{__version__}*
*Created: {datetime.now().strftime('%Y-%m-%d')}*
"""
    with open(docs_dir / "AI_INTEGRATION.md", 'w', encoding='utf-8') as f:
        f.write(content)


def _create_docs_readme(docs_dir: Path) -> None:
    """Create README for the docs directory"""
    content = f"""# SpecPulse Documentation

This directory contains documentation for SpecPulse AI integration.

## Available Documents

### [AI_FALLBACK_GUIDE.md](AI_FALLBACK_GUIDE.md)

Fallback procedures when CLI commands fail. Essential for AI assistants.

### [AI_INTEGRATION.md](AI_INTEGRATION.md)

AI platform integration guide with command reference and workflows.

## Quick Reference

### For AI Assistants

```bash
# If CLI fails:
.specpulse/docs/AI_FALLBACK_GUIDE.md

# For integration patterns:
.specpulse/docs/AI_INTEGRATION.md
```

### For Users

```bash
specpulse doctor        # Check project health
specpulse doctor --fix  # Auto-fix issues
specpulse --help        # Get help
```

## External Resources

- **GitHub**: https://github.com/specpulse/specpulse
- **PyPI**: https://pypi.org/project/specpulse/

---

*Documentation for SpecPulse v{__version__}*
"""
    with open(docs_dir / "README.md", 'w', encoding='utf-8') as f:
        f.write(content)
