[command]
name = "pulse"
description = "Initialize SpecPulse features"

[command.subcommands.init]
description = "Initialize a new feature with proper structure"
usage = "/pulse init <feature-name>"

[[command.subcommands.init.steps]]
action = "run_script"
script = "scripts/pulse-init.sh"
args = ["{{feature_name}}"]

[[command.subcommands.init.steps]]
action = "create_files"
files = [
    "specs/{{branch_name}}/spec.md",
    "plans/{{branch_name}}/plan.md",
    "tasks/{{branch_name}}/tasks.md"
]

[[command.subcommands.init.steps]]
action = "update_context"
file = "memory/context.md"
content = """
## Active Feature: {{feature_name}}
- Feature ID: {{feature_id}}
- Branch: {{branch_name}}
- Started: {{timestamp}}
"""

[[command.subcommands.init.steps]]
action = "git_branch"
branch = "{{branch_name}}"

[command.response]
template = """
✅ Feature initialized: {{feature_name}}
- Branch: {{branch_name}}
- Spec: specs/{{branch_name}}/spec.md
- Plan: plans/{{branch_name}}/plan.md
- Tasks: tasks/{{branch_name}}/tasks.md

Next: Use /spec create to define requirements
"""