description = "Generate and manage task breakdowns"
prompt = """
Handle the /task command with arguments: {{args}}

Parse arguments to determine action:
- If "update": Update task status
- If "status": Show progress
- Otherwise: Generate task breakdown

## For /task breakdown or /task:
1. Read implementation plan from @{plans/*/plan.md}

2. Generate tasks from plan:
   - Create task categories:
     • Critical Path (Phase 0)
     • Phase 1: Foundation
     • Phase 2: Core Features
     • Phase 3: Polish
     • Phase 4: Testing

   - For each task:
     • Use T[XXX] format (T001, T002)
     • Include clear description
     • Mark dependencies
     • Estimate complexity (S/M/L/XL)
     • Assign priority

3. Write tasks to tasks/XXX-feature/tasks.md
4. Run cross-platform validation:
   - Windows: !{powershell scripts/pulse-task.ps1 "XXX-feature"}
   - Linux/macOS: !{bash scripts/pulse-task.sh "XXX-feature"}
   - Fallback: !{python scripts/pulse-task.py "XXX-feature"}

## For /task update:
1. Read current tasks from @{tasks/*/tasks.md}
2. Ask which tasks to update
3. Mark tasks as completed/in-progress
4. Add newly discovered tasks
5. Update dependencies and blockers
6. Save updated task list
7. Run cross-platform validation:
   - Windows: !{powershell scripts/pulse-task.ps1 "XXX-feature"}
   - Linux/macOS: !{bash scripts/pulse-task.sh "XXX-feature"}
   - Fallback: !{python scripts/pulse-task.py "XXX-feature"}

## For /task status:
1. Read current tasks
2. Run cross-platform analysis:
   - Windows: !{powershell scripts/pulse-task.ps1 "XXX-feature"}
   - Linux/macOS: !{bash scripts/pulse-task.sh "XXX-feature"}
   - Fallback: !{python scripts/pulse-task.py "XXX-feature"}
3. Count completed vs total
4. Show current phase progress
5. List any blockers
6. Estimate remaining work
7. Display progress summary

Task Format:
```markdown
- [ ] T001: [S] Set up project structure
- [ ] T002: [M] Create database schema
- [x] T003: [L] Implement authentication
```

Examples:
- /task breakdown
- /task update
- /task status
"""