ai:
  primary: claude
constitution:
  enforce: true
  principles:
  - simplicity_first
  - test_driven
  - single_responsibility
  - documented
  - secure_by_design
  strict_mode: false
conventions:
  branch_naming: '{number:03d}-{feature-name}'
  spec_naming: SPEC-{number:03d}
  task_naming: TASK-{number:03d}
integrations:
  ci_cd:
    provider: github_actions
    trigger_on:
    - plan_approved
    - tests_passed
  git:
    auto_commit: true
    commit_template: '[SpecPulse] {action}: {description}'
project:
  created: '2025-10-05T02:53:53.450953'
  name: SpecPulse
  type: web
templates:
  plan: templates/plan.md
  spec: templates/spec.md
  task: templates/task.md
validation:
  coverage:
    e2e_test: 40
    integration_test: 60
    unit_test: 80
  required_sections:
    plan:
    - architecture
    - phases
    - technology_stack
    spec:
    - requirements
    - user_stories
    - acceptance_criteria
    task:
    - dependencies
    - estimates
    - assignments
version: 1.4.5
workflow:
  stages:
  - draft
  - review
  - approved
  - implementation
  - testing
  - deployed
  transitions:
    approved_to_implementation:
      requires:
      - plan_generated
      - tasks_created
    draft_to_review:
      requires:
      - complete_specification
      - no_clarifications_pending
    review_to_approved:
      requires:
      - peer_review
      - validation_passed
